### ISSUE TITLE
How to reproduce the results in your paper?

### ISSUE THREAD

**Issue by z-x-yang** [tztztztztz/eql.detectron2#8]
I want to reproduce your paper's results, but it seems like you changed some settings (such as Scale jitter) in this repository.

May I ask for the code with the original setting in your paper? Or how to modify this repository to reach that?

Thanks in advance!

**Comment by tztztztztz** [comment]
Sorry, the origin code is based on a internal codebase, which is confidential.

If you want to match the origin setting in this repo, here are some modifications to make:

1. single scale training
INPUT:
  MIN_SIZE_TRAIN: (800, )

2. 2000 training proposals
RPN:
  POST_NMS_TOPK_TRAIN: 2000

3. class agnostic mask head 
ROI_MASK_HEAD:
  CLS_AGNOSTIC_MASK = True

4. Use smooth L1 loss instead of L1
RPN:
 SMOOTH_L1_BETA = 1.0 / 9.0
ROI_BOX_HEAD:
  SMOOTH_L1_BETA = 1.0

**Comment by z-x-yang** [comment]
THX!
